name: Sphinx Build

on:
  push:
    branches:
      - main

jobs:
  sphinx-build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build docs
        run: sphinx-build . html
