name: Sphinx Build

on:
  push:
    branches:
      - main

jobs:
  sphinx-build:
    runs-on: self-hosted, Linux

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install git
        run: apt install -y git

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install python depencencies
        run: pip3 install sphinx furo sphinx-copybutton myst-parser

      - name: Build docs
        run: sphinx-build . html

      - name: Deploy pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./html
